config/routes.rb
FirstApp::Application.routes.draw do
  resources :avatars

  devise_for :users, :controllers => { :registrations => "registrations" }
  resque_constraint = lambda do |request|
    request.env['warden'].authenticate? and request.env['warden'].user.admin?
  end

  constraints resque_constraint do
    mount MongodbLogger::Server.new, :at => "/mongodb"
  end

  
  resources :users do
    member do
      get :following, :followers
      get :crop
      get :dashboard
      get :achievements
      get :stats
      get :facebook_friends
    end
  end
  
  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
    end
  end
  
  resources :courses do
    member do
      post :rate
      get :bookmark
    end
    get :autocomplete_tag_name, :on => :collection
    resources :course_modules do
      collection do
        get :reorder
        put :reorder_save
      end
    end
  end
  
  resources :linkedin_profile
  match 'linkedin_profile/:slug/edit' => 'linkedin_profile#edit'
  
  match "/images/uploads/*path" => "gridfs#serve"
  resources :avatars

  get "courses/index"
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  root to: 'static_pages#home'
  match '/help', to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/signup',  to: 'users#new'
  match '/auth/:service/callback' => 'services#create' 
  resources :services, :only => [:index, :create, :destroy]  
  
  match 'statistics/detail/:id/:class_id' => 'statistics#show', :as => 'statistic'
  match 'statistics/:id' => 'statistics#index'
  mount Resque::Server, :at => "/resque"
  match 'course_landing' => 'courses#course_landing', :as => 'course_landing'
  match 'search' => 'searches#index'
  match 'courses' => 'courses#index'
  
  match 'my_courses' => 'courses#my_courses'
  match 'manage/courses' => 'courses#manage'

  match 'courses/:id/start' => 'courses#start'
  match 'courses/:course_id/course_modules/:id/quiz/' => 'course_modules#quiz_answers'
  match 'courses/:course_id/course_modules/:id/next' => 'course_modules#next'
  match 'courses/:course_id/course_modules/:id/previous' => 'course_modules#previous'
  match 'courses/:course_id/course_modules/:id/:status/' => 'course_modules#update_stat'


  get "forums/index"
  resources :forums
  resources :topics
  resources :forumposts

  match 'show_forum' => 'forums#show'
  match 'new_forum' => 'forums#new'

  match 'new_forumpost' => 'forumposts#new'
  match 'edit_forumpost' => 'forumposts#edit'












end

app/models/topic.rb
class Topic < ActiveRecord::Base

	attr_accessible :name, :last_poster_id, :last_post_at, :forum_id, :user_id 
	attr_accessor :description
    
	belongs_to :forum
	belongs_to :user

	has_many :forumposts, :dependent => :destroy

	validates :name, :presence => true, :uniqueness => true, 
			:length => { :maximum => 255, :too_long => "%{count} characters is the max allowed" }


end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
    @forum = Topic.first.forum
  end

  def show
    @topic = Topic.find(params[:id])
    @forum = Forum.find(@topic.forum)
    @course = Course.new
    if @forum.course_id
	@course = Course.where(:id=>@forum.course_id)
    end
  end

  def new
    @topic = Topic.new
    @course = Course.new
    @forum = Forum.find(params[:forum_id])
   if @forum.course_id
	@course = Course.where(:id=>@forum.course_id)
    end
    @forumpost = Forumpost.new
  end

  
  def create
      @topic = Topic.new( :name => params[:topic][:name], :last_poster_id => current_user.id, :last_post_at => Time.now, 
		:forum_id => params[:topic][:forum_id], :user_id => current_user.id)

	@forum = Forum.find(params[:topic][:forum_id])
    
	if @topic.save
		@forumpost = Forumpost.new(:content => params[:topic][:description], :topic_id => @topic.id, :user_id => current_user.id)
		@topic = Topic.new(:name => params[:topic][:name], :last_poster_id => current_user.id, :last_post_at => Time.now, 
		:forum_id => params[:topic][:forum_id])

		if@forumpost.save
			redirect_to show_forum_path(:id => @topic.forum_id ), :notice => "Successfully created forum topic."
		else
			redirect_to show_forum_path(:id => @topic.forum_id ), :notice => "Error while creating forum topic."
		end
	else 
		redirect_to show_forum_path(:id => @topic.forum_id ), :notice => "Error while creating forum topic."
    	end
  end


  def edit
    @topic = Topic.find(params[:id])
  end

  def update
    @topic = Topic.find(params[:id])
    if @topic.update_attributes(params[:topic])
      redirect_to "/forums/#{@topic.forum_id}"
    else
      render :action => 'edit'
    end
  end

  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy
    redirect_to "/forums/#{@topic.forum_id}"
  end
end

app/views/topics/_form.html.erb
<div class="container-fluid">

<%= form_for @topic do |f| %>
  <%= f.error_messages %>
  <% if params[:forum_id] %>
	<input type="hidden" id="topic_forum_id" name="topic[forum_id]" value="<%= params[:forum_id] %>" />
  <% end %>
  
	<div class="row-fluid">
	  <div class="span6">
    		<%= f.label :name %><br />
    		<%= f.text_field :name, :class=>'input-full' %>
  		
		<%= f.label :description %><br />
    		<%= f.text_area :description, :class=>'input-full' %>

		</br>
		<div>
			<%= f.submit :class => "btn btn-primary"%>
		</div>
  	  </div>
	</div>

  
<% end %>

</div>

app/views/topics/edit.html.erb
<h2>Edit Topic </h2>

<%= render 'form' %>

<p>
  <%= link_to "Show", @topic %> |
  <%= link_to "View All", topics_path %>
</p>

app/views/topics/index.html.erb
<div>
	<h2> Topics </h2>
</div>

<div>
<table>
  <tr>
    <th width="50%">Name</th>
    <th width="10%">Last Poster</th>
    <th width="40%">Last Post At</th>
  </tr>
  <% for topic in @topics %>
    <tr>
      <td><%= topic.name %></td>
      <td><%= topic.last_poster_id %></td>
      <td><%= topic.last_post_at %></td>
    </tr>
  <% end %>
</table>
</div>

<div>
	<p><%= link_to "New Topic", new_topic_path %></p>
</div>

app/views/topics/new.html.erb
<div class="container-fluid">
</br>
<div class="row-fluid">
<div class="span6">
<% if !@course.name.blank? %>
	<h3>Course Name: <%= @course.name %></h2>
<% end %>
<h4> Forum Name: <%= @forum.name %> </h2>
</br>
<h4> Create Topic </h2>
</div>
</div>

</br>

<div class="container">
	<%= render 'form' %>
</div>

<div>
<%= link_to "Back to Forum", :controller=>"forums", :action=>"show", :id=>@forum.id %></p>
</div>

</div>

app/views/topics/show.html.erb
<div class="container-fluid">
</br>

<div class="row-fluid">
<div class="span6">
<% if @forum.course_id %>
	<h3>Course Name: <%= @course.name %></h3>
<% end %>
<h4> Forum Name: <%= @forum.name %> </h4>
<h4> Topic Name: <%= @topic.name %> </h4>
</br>
<h4>Topic Posts</h4>
</div>
</div>


</br></br>

<div class="row-fluid">
    <div class="span10"></div>
	<div class="span2">
		<%= link_to "Reply", :controller => "forumposts", :action => "new", :topic_id => @topic %>
    </div>
<div class="span12">
<div class="table table-hover">
<body>
<table class="table-bordered table-striped">
	<tr>
		<th width="20%">Posted By</th>
		<th width="60%">Post Content</th>
		<th width="20%">Created</th>
	</tr>

<% for forumpost in @topic.forumposts %>
	
	<tr>
		<td><%= link_to forumpost.user.name, forumpost.user %></td>
		<td class="right"><%= forumpost.content %></td>
		<td><%= forumpost.created_at.strftime("%b %d, %Y %I:%M %p") %>
	</tr>
<% end %>

</table>
</body>
</div>
</div>
</div>


</br> 

<div>
  	<%= link_to "View All Topics", forum_path(@topic.forum_id) %>
</div>