config/routes.rb
FirstApp::Application.routes.draw do
  resources :avatars

  devise_for :users, :controllers => { :registrations => "registrations" }
  resque_constraint = lambda do |request|
    request.env['warden'].authenticate? and request.env['warden'].user.admin?
  end

  constraints resque_constraint do
    mount MongodbLogger::Server.new, :at => "/mongodb"
  end

  
  resources :users do
    member do
      get :following, :followers
      get :crop
      get :dashboard
      get :achievements
      get :stats
      get :facebook_friends
    end
  end
  
  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
    end
  end
  
  resources :courses do
    member do
      post :rate
      get :bookmark
    end
    get :autocomplete_tag_name, :on => :collection
    resources :course_modules do
      collection do
        get :reorder
        put :reorder_save
      end
    end
  end
  
  resources :linkedin_profile
  match 'linkedin_profile/:slug/edit' => 'linkedin_profile#edit'
  
  match "/images/uploads/*path" => "gridfs#serve"
  resources :avatars

  get "courses/index"
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  root to: 'static_pages#home'
  match '/help', to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/signup',  to: 'users#new'
  match '/auth/:service/callback' => 'services#create' 
  resources :services, :only => [:index, :create, :destroy]  
  
  match 'statistics/detail/:id/:class_id' => 'statistics#show', :as => 'statistic'
  match 'statistics/:id' => 'statistics#index'
  mount Resque::Server, :at => "/resque"
  match 'course_landing' => 'courses#course_landing', :as => 'course_landing'
  match 'search' => 'searches#index'
  match 'courses' => 'courses#index'
  
  match 'my_courses' => 'courses#my_courses'
  match 'manage/courses' => 'courses#manage'

  match 'courses/:id/start' => 'courses#start'
  match 'courses/:course_id/course_modules/:id/quiz/' => 'course_modules#quiz_answers'
  match 'courses/:course_id/course_modules/:id/next' => 'course_modules#next'
  match 'courses/:course_id/course_modules/:id/previous' => 'course_modules#previous'
  match 'courses/:course_id/course_modules/:id/:status/' => 'course_modules#update_stat'


  get "forums/index"
  resources :forums
  resources :topics
  resources :forumposts

  match 'show_forum' => 'forums#show'
  match 'new_forum' => 'forums#new'

  match 'new_forumpost' => 'forumposts#new'
  match 'edit_forumpost' => 'forumposts#edit'












end

app/models/forumpost.rb
class Forumpost < ActiveRecord::Base

	attr_accessible :content, :topic_id, :user_id

	belongs_to :topic
	belongs_to :user
	
end

app/controllers/forumposts_controller.rb
# app/controllers/posts_controller.rb

class ForumpostsController < ApplicationController
  def index
    @forumposts = Forumpost.all
  end

  def show
    @forumpost = Forumpost.find(params[:id])
  end

  def new
    @forumpost = Forumpost.new
    @course = Course.new
    @topic = Topic.find(params[:topic_id])
    @forum = Forum.where(:id=>@topic.forum_id)	
  end


  def create
   @forumpost = Forumpost.new(:content => params[:forumpost][:content], 
	:topic_id => params[:forumpost][:topic_id], :user_id => current_user.id)
   if @forumpost.save
	@topic = Topic.where(:id=>@forumpost.topic_id)
	@topic.update_all(:last_poster_id => current_user.id, :last_post_at => Time.now)
	flash[:notice] = "Successfully created post."
      redirect_to "/topics/#{@forumpost.topic_id}"
    else
      render :action => 'new'
    end
  end


  def edit
    @forumpost = Forumpost.find(params[:id])
  end

  def update
    @forumpost = Forumpost.find(params[:id])
    if @forumpost.update_attributes(params[:forumpost])
	@topic = Topic.find(@forumpost.topic_id)
	@topic.update_attributes(:last_poster_id => current_user.id, :last_post_at => Time.now)
	flash[:notice] = "Successfully updated forumpost."
      redirect_to forums_url 
    else
      render :action => 'edit'
    end
  end

  def destroy
    @forumpost = Forumpost.find(params[:id])
    @forumpost.destroy
    redirect_to forumposts_url, :notice => "Successfully destroyed forumpost."
  end
end

app/views/forumposts/_form.html.erb
<div class="container-fluid">
<%= form_for @forumpost do |f| %>
  <%= f.error_messages %>
  <% if params[:topic_id] %>
	<input type="hidden" id="topic_id" name="forumpost[topic_id]" value="<%= params[:topic_id] %>" />
  <% end %>
  
<div class="row-fluid">
  <div class="span6">

    <%= f.label :content %><br />
    <%= f.text_area :content %>
  
	</br>
	<div>
	    <%= f.submit "Create Post" %>
	</div>
  </div>
<div>

<% end %>
</div>

app/views/forumposts/edit.html.erb
<% title "Edit Forumpost" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @forumpost %> |
  <%= link_to "View All", forumposts_path %>
</p>

app/views/forumposts/index.html.erb
<h2> Posts </h2>


<div class="row-fluid">
<div class="span12">
<div class="table table-hover">
<body>
<table>
  <tr>
	<th width="30%">Posted By</th>
	<th width="20%">Post Date</th>
	<th width="50%">Content</th>
  </tr>
  <% for forumpost in @forumposts %>
    <tr>
	<td><%= forumpost.user.slug %></td>
	<td><%= forumpost.created_at %></td>
      <td><%= forumpost.content %></td>
    </tr>
  <% end %>
</table>
</body>
</div>
</div>
</div>


<p><%= link_to "New Post", new_forumpost_path %></p>

app/views/forumposts/new.html.erb
<div class="container-fluid">
</br>

<div class="row-fluid">
<div class="span6">
<h4> Forum Name: <%= @forum.name %> </h4>
<h4> Topic Name: <%= @topic.name %> </h4>
</br>
<h4>New Post</h4>
</div>
</div>

</br></br>

<div class="container">
	<%= render 'form' %>
</div>

<div>
<%= link_to "Back to Topic", :controller=>"topics", :action=>"show", :id=>@topic %>
</div>

</div>

app/views/forumposts/show.html.erb

<h2> Post Content </h2>

<p>
  <strong>Content:</strong>
  <%= @forumpost.content %>
</p>

<p>
  <%= link_to "Edit", edit_forumpost_path(@forumpost) %> |
  <%= link_to "Delete", @forumpost, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", forumposts_path %>
</p>