config/routes.rb
FirstApp::Application.routes.draw do
  resources :avatars

  devise_for :users, :controllers => { :registrations => "registrations" }
  resque_constraint = lambda do |request|
    request.env['warden'].authenticate? and request.env['warden'].user.admin?
  end

  constraints resque_constraint do
    mount MongodbLogger::Server.new, :at => "/mongodb"
  end

  
  resources :users do
    member do
      get :following, :followers
      get :crop
      get :dashboard
      get :achievements
      get :stats
      get :facebook_friends
    end
  end
  
  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
    end
  end
  
  resources :courses do
    member do
      post :rate
      get :bookmark
    end
    get :autocomplete_tag_name, :on => :collection
    resources :course_modules do
      collection do
        get :reorder
        put :reorder_save
      end
    end
  end
  
  resources :linkedin_profile
  match 'linkedin_profile/:slug/edit' => 'linkedin_profile#edit'
  
  match "/images/uploads/*path" => "gridfs#serve"
  resources :avatars

  get "courses/index"
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  root to: 'static_pages#home'
  match '/help', to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/signup',  to: 'users#new'
  match '/auth/:service/callback' => 'services#create' 
  resources :services, :only => [:index, :create, :destroy]  
  
  match 'statistics/detail/:id/:class_id' => 'statistics#show', :as => 'statistic'
  match 'statistics/:id' => 'statistics#index'
  mount Resque::Server, :at => "/resque"
  match 'course_landing' => 'courses#course_landing', :as => 'course_landing'
  match 'search' => 'searches#index'
  match 'courses' => 'courses#index'
  
  match 'my_courses' => 'courses#my_courses'
  match 'manage/courses' => 'courses#manage'

  match 'courses/:id/start' => 'courses#start'
  match 'courses/:course_id/course_modules/:id/quiz/' => 'course_modules#quiz_answers'
  match 'courses/:course_id/course_modules/:id/next' => 'course_modules#next'
  match 'courses/:course_id/course_modules/:id/previous' => 'course_modules#previous'
  match 'courses/:course_id/course_modules/:id/:status/' => 'course_modules#update_stat'


  get "forums/index"
  resources :forums
  resources :topics
  resources :forumposts

  match 'show_forum' => 'forums#show'
  match 'new_forum' => 'forums#new'

  match 'new_forumpost' => 'forumposts#new'
  match 'edit_forumpost' => 'forumposts#edit'












end

app/models/search.rb
class Search < ActiveRecord::Base
  
  def self.search(params)
    results_on_page = 10 # this needs to be a property.
    page = 0
    if params[:page] 
      page = params[:page].to_i - 1
    end
    from = page * results_on_page
    Tire.search  do
    #tire.search :per_page => 2, :page => 1 do
      query do
        boolean do
          must { string params[:query], default_operator: "AND" } if params[:query].present?
          must { string "*", default_operator: "AND" } if !params[:query].present?
          must { term :course_rating, params[:course_rating] } if params[:course_rating].present?
          must { term :user_id, params[:author] } if params[:author].present?
          must { term :category, params[:industry] } if params[:industry].present?
        end
        page = (1 || 1).to_i
        
        
      end
      # User from and size for pagination
      from from
      size results_on_page
      # raise to_curl
    end
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def index
    
      # Facets need to be queried seperately for each model type.
      @facets = Course.facets(params)
      
      @courses = Search.search(params)
      
  end
  
end

app/helpers/searches_helper.rb
module SearchesHelper
  def paginate_elastic results
    totalResults = results.results.total
    results_on_page = 10 # this needs to be a property.
    
    pages = totalResults / results_on_page
    if totalResults % results_on_page != 0
      pages += 1 
    end
    
    
    # If page is not set then make page 1.
    page = params[:page].to_i
    if !params[:page]
      page = 1
    end
    
    # Sorry lots of wacky calculations to get the number of items before and after current page.
    maxPageAddition = 0
    if page - 6 < 1 
      maxPageAddition = 6 - page
    end
    
    minPageAddition = 0
    if page + 4 > pages
      minPageAddition = (page + 4) - pages
    end 
    
    minPage = page - 5 - minPageAddition > 1? page - 5 - minPageAddition : 1
    maxPage = page + 4 + maxPageAddition > pages ? pages : page+4+maxPageAddition
    
    
    searchParams = Hash.new
    searchParams[:page] = page
    searchParams[:minPage] = minPage
    searchParams[:maxPage] = maxPage
    searchParams[:totalPages] = pages
    render 'searches/pagination', :searchParams => searchParams
  end
end

app/views/searches/_course_facets.html.erb
<h3>Filters</h3>
<% if @facets.results.facets['course_ratings']['terms'].size > 0%>
<div id="facets">
  <h4>Course Ratings</h4>
  <ul>
    
    <% @facets.results.facets['course_ratings']['terms'].each do |facet| 
      temp = params.dup
      temp.delete :page
      %>
      <li>
      <%= link_to_unless_current facet['term'].to_s + " stars", temp.merge(course_rating: facet['term']) %>
      <% if params[:course_rating] == facet['term'].to_s 
        temp.delete :course_rating
      %>
        (<%= link_to "remove", temp %>)
      <% else %>
        (<%= facet['count'] %>)
      <% end %>
      </li>
      
      
    <% end %>
  </ul>
</div>
<% end %>
<% if @facets.results.facets['authors']['terms'].size > 0%>
<div id="facets">
  <h4>Course Creator</h4>
  <ul>
    <% @facets.results.facets['authors']['terms'].each do |facet| 
      username = User.find(facet['term']).name
      temp = params.dup
      temp.delete :page
      %>
      <li>
        <%= link_to_unless_current username, temp.merge(author: facet['term']) %>
        <% if params[:author] == facet['term'].to_s 
          temp.delete :author
        %>
          (<%= link_to "remove", temp %>)
        <% else %>
          (<%= facet['count'] %>)
        <% end %>
      </li>
    <% end %>
  </ul>
</div>
<% end %>
<% if @facets.results.facets['industries']['terms'].size > 0%>
<div id="facets">
  <h4>Industry</h4>
  <ul>
    <% @facets.results.facets['industries']['terms'].each do |facet| 
      temp = params.dup
      temp.delete :page
      %>
      <li>
        <%= link_to_unless_current facet['term'].camelize, temp.merge(industry: facet['term']) %>
        <% if params[:industry] == facet['term'].to_s 
          temp.delete :industry
        %>
          (<%= link_to "remove", temp %>)
        <% else %>
          (<%= facet['count'] %>)
        <% end %>
      </li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/searches/_course_result.html.erb
<%
  # Need to find a more effiecient way of doing this
  bookmark = current_user.bookmarks.where(:course_id => result.id).first
%>
  <tr>
    <td>
      <div class="title"><%= link_to result.name, course_path(result) %></div>
      <div class="action" style="float:right;">
        <% if !bookmark %>
          <%= link_to "Bookmark", course_path(result)+"/bookmark", :class => "btn btn-small btn-primary bookmark", :remote => true %>
        <% else %>
          <span class="label">bookmarked</span>
        <% end %>
      </div>
      <div class="description"><%= truncate result.description, :length => 300 %></div>
      <%= ratings_for Course.find(result.id), :static %>
    </td>
  </tr>

app/views/searches/_pagination.html.erb
<div class="apple_pagination">
  <% if searchParams[:page] == 1 %>
    <span class="disabled previous_page">← Previous</span>
  <% else %>
    <%= link_to "← Previous", params.merge(page: searchParams[:page] - 1), :class => "previous_page" %>
  <% end %>
    <% (searchParams[:minPage]..searchParams[:maxPage]).each do |i| %>
      <% if i==searchParams[:page]%>
        <em class="current"><%= i %></em>
      <% else %>
        <%= link_to i, params.merge(page: i) %>
      <% end %>
    <% end %>
  <% if searchParams[:page] == searchParams[:totalPages] %>
    <span class="disabled next_page">Next →</span>
  <% else %>
    <%= link_to "Next →", params.merge(page: searchParams[:page] + 1), :class => "next_page" %>
  <% end %>
</div>

app/views/searches/_show_rating.html.erb
<%= link_to_unless_current "test", params.merge(course_rating: rating) %>
<div id="ajaxful_rating_no-small_course_3" class="ajaxful-rating-wrapper">
  <ul class="ajaxful-rating">
    <li style="width: <%= (rating.to_f / 5)*100 %>%" class="show-value">
      Global rating average: 0.0 out of 5
    </li>
    <li>
      <span title="Global rating average: 0.0 out of 5" class="stars-1">0.0</span>
    </li>
    <li>
      <span title="Global rating average: 0.0 out of 5" class="stars-2">0.0</span>
    </li>
    <li>
      <span title="Global rating average: 0.0 out of 5" class="stars-3">0.0</span>
    </li>
    <li>
      <span title="Global rating average: 0.0 out of 5" class="stars-4">0.0</span>
    </li>
    <li>
      <span title="Global rating average: 0.0 out of 5" class="stars-5">0.0</span>
    </li>
  </ul>
</div>
<div class="rating-count">
  
  <% if params[:course_rating] == rating.to_s 
    temp = params.dup
    temp.delete :course_rating
  %>
    (<%= link_to "remove", temp %>)
  <% else %>
    (<%= count %>)
  <% end %>  
</div>

app/views/searches/_user_result.html.erb
<tr>
  <td>
    <div class="title"><%= link_to result.name, user_path(result) %> - User Bio will go here.</div>
  </td>
</tr>

app/views/searches/index.html.erb
<div class="container-fluid search-results">
  <div class="row-fluid">
    <div class="span3 facets">
      <%= render 'course_facets' %>
    </div>
    <div class="span9">
      <table class="table table-hover search-results">
        <% 
        @courses.results.each do |result| 
          if result.type == 'course'
            %>
            <%= render 'course_result', :result => result %>
          <% 
          else
             %>
            <%= render 'user_result', :result => result %>
             <%
          end
        end %>
      </table>
      <%= paginate_elastic @courses%>
    </div>
  </div>
</div>