config/routes.rb
FirstApp::Application.routes.draw do
  resources :avatars

  devise_for :users, :controllers => { :registrations => "registrations" }
  resque_constraint = lambda do |request|
    request.env['warden'].authenticate? and request.env['warden'].user.admin?
  end

  constraints resque_constraint do
    mount MongodbLogger::Server.new, :at => "/mongodb"
  end

  
  resources :users do
    member do
      get :following, :followers
      get :crop
      get :dashboard
      get :achievements
      get :stats
      get :facebook_friends
    end
  end
  
  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
    end
  end
  
  resources :courses do
    member do
      post :rate
      get :bookmark
    end
    get :autocomplete_tag_name, :on => :collection
    resources :course_modules do
      collection do
        get :reorder
        put :reorder_save
      end
    end
  end
  
  resources :linkedin_profile
  match 'linkedin_profile/:slug/edit' => 'linkedin_profile#edit'
  
  match "/images/uploads/*path" => "gridfs#serve"
  resources :avatars

  get "courses/index"
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  root to: 'static_pages#home'
  match '/help', to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/signup',  to: 'users#new'
  match '/auth/:service/callback' => 'services#create' 
  resources :services, :only => [:index, :create, :destroy]  
  
  match 'statistics/detail/:id/:class_id' => 'statistics#show', :as => 'statistic'
  match 'statistics/:id' => 'statistics#index'
  mount Resque::Server, :at => "/resque"
  match 'course_landing' => 'courses#course_landing', :as => 'course_landing'
  match 'search' => 'searches#index'
  match 'courses' => 'courses#index'
  
  match 'my_courses' => 'courses#my_courses'
  match 'manage/courses' => 'courses#manage'

  match 'courses/:id/start' => 'courses#start'
  match 'courses/:course_id/course_modules/:id/quiz/' => 'course_modules#quiz_answers'
  match 'courses/:course_id/course_modules/:id/next' => 'course_modules#next'
  match 'courses/:course_id/course_modules/:id/previous' => 'course_modules#previous'
  match 'courses/:course_id/course_modules/:id/:status/' => 'course_modules#update_stat'


  get "forums/index"
  resources :forums
  resources :topics
  resources :forumposts

  match 'show_forum' => 'forums#show'
  match 'new_forum' => 'forums#new'

  match 'new_forumpost' => 'forumposts#new'
  match 'edit_forumpost' => 'forumposts#edit'












end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :getUnreadMessageCount, :only =>[:manage, :my_courses]
  
  #autocomplete :tag, :name, :class_name => 'ActsAsTaggableOn::Tag' # <- New
  
  def index
    @courses = Course.all
  end
  
  def edit
    @course = Course.find(params[:id])
  end
  
  def show
      @course = Course.find(params[:id])
      
      respond_to do |format|
        format.html # new.html.erb
        format.xml  { render :xml => @course }
      end
  end
   
  def start
      @course = Course.find(params[:id])
      @statistics = Statistic.where(:user_id => current_user.id).where(:course_id => @course.id).where(:status => "done")
      
      @course_history = current_user.course_histories.where(:course_id => @course.id).first
      
      if !@course_history
        @course_history = current_user.course_histories.build(:course_id => @course.id, :status => "in_progress")
        @course_history.save
      end
      
      respond_to do |format|
        format.html # new.html.erb
        format.xml  { render :xml => @course }
      end
  end 
   
  def new
    @course = Course.new
  
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @question }
    end
  end
  
  def create
    @course = current_user.courses.build(params[:course])
    if @course.save
      flash[:success] = "Course created!"
      redirect_to edit_course_path(@course);
    else
      render 'new'
    end
  end
  
  def update
      @course = current_user.courses.where(:id => params[:id]).first
      
      # Is there a better way of doing this?
      if params[:publish] 
        @course.published = true
      elsif params[:un_publish]
        @course.published = false
      end 
      
      if @course.update_attributes(params[:course])
         flash[:success] = "Course saved!"
         redirect_to edit_course_path(@course);
      else
         render :action => 'edit'
      end
   end

  def destroy
    @course = current_user.courses.where(:id => params[:id]).first
    if @course.present?
      @course.destroy
      flash[:success] = "Course deleted!"
    end
    # in both cases, redirect to root_path
    redirect_to courses_path
  end
  
  def manage
    set_admin_mode(true)
    @courses = current_user.courses
  end
  
  def my_courses
    set_admin_mode(false)
    @course_histories = current_user.course_histories
    @bookmarks = current_user.bookmarks
  end
  
  def search
    if(params[:query].empty?)
      @courses = Course.where("published = 1 and privacy='Public'")
    else
      @facets = Course.facets(params)
      @courses = Course.search(params)
    end
  end
  
  def video
    @course = Course.find(params[:id])
  end
  
  def rate
    @course = Course.find(params[:id])
    @course.rate(params[:stars], current_user, params[:dimension])
    respond_to do |format|
      format.js
    end
  end
  
  def bookmark
    puts request.method
    if params[:remove]
      bookmark = current_user.bookmarks.where(:course_id => params[:id]).first
      bookmark.destroy
    else
      bookmark = current_user.bookmarks.build(:course_id => params[:id])
      bookmark.save
    end
    respond_to do |format|
      format.json { head :ok }
      format.html { redirect_to my_courses_path }
    end

  end
  
end

app/views/courses/_courses_admin_menu.html.erb
<% content_for :sub_menu do %>
<div class="navbar navbar-static-top courses_navbar">
  <div class="navbar-inner sub-nav">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
      <nav class="nav-collapse">
        <ul class="nav pull-left">
          <li class="<%= activate_menu("dashboard", highlight) %>">
            <%= link_to dashboard_user_path(current_user) do %> 
              <i class="icon-home icon-white"></i>Dashboard
            <% end %>  
          </li>
          <li class="<%= activate_menu("courses", highlight) %>">
            <%= link_to manage_courses_path do %> 
              <i class="icon-book icon-white"></i>Courses
            <% end %>  
          </li>
          <li class="<%= activate_menu("followers", highlight) %>">
            <%= link_to followers_user_path(current_user) do %>
              <i class="icon-user icon-white"></i>Followers
            <% end %>
          </li>
          <li class="<%= activate_menu("stats", highlight) %>">
            <%= link_to stats_user_path(current_user) do %>
              <i class="icon-signal icon-white"></i>Stats
            <% end %>
          </li>
          <li class="<%= activate_menu("messages", highlight) %>">
            <%= link_to :conversations do %>
              <i class="icon-comment icon-white"></i>Messages
            <% end %>
          </li>
          <li class="<%= activate_menu("settings", highlight) %>">
            <%= link_to '#' do %>
              <i class="icon-list-alt icon-white"></i>Settings
            <% end %>
          </li>
        </ul>
        <ul class="nav pull-right">
          <li>
            <%= link_to "Switch to Course Taker View", my_courses_path, :class => 'btn btn-success btn-mini admin_swtich_btn'%>
          </li>
        </ul>
      </nav>
    </div>
  </div>
</div>
<script>
<% flash.each do |key, value| %>
    	$.jGrowl("<%= value %>");
<% end %>
</script>
<% end %>

app/views/courses/_courses_menu.html.erb
<% content_for :sub_menu do %>
<div class="navbar navbar-static-top courses_navbar">
  <div class="navbar-inner sub-nav">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
      <nav class="nav-collapse">
        <ul class="nav pull-left">
          <li class="<%= activate_menu("dashboard", highlight) %>">
            <%= link_to dashboard_user_path(current_user) do %> 
              <i class="icon-home icon-white"></i>Dashboard
            <% end %>  
          </li>
          <li class="<%= activate_menu("courses", highlight) %>">
            <%= link_to my_courses_path do %> 
              <i class="icon-book icon-white"></i>Courses
            <% end %>  
          </li>
          <li class="<%= activate_menu("achievements", highlight) %>">
            <%= link_to achievements_user_path(current_user) do %>
              <i class="icon-star icon-white"></i>Achievements
            <% end %>
          </li>
          
          <li class="<%= activate_menu("messages", highlight) %>">
            <%= link_to :conversations do %>
              <i class="icon-comment icon-white"></i>Messages
              <% if @unread_message_count > 0 %>
              (<%= @unread_message_count %>)
              <% end %>
            <% end %>
          </li>
        </ul>
	<% if can? :create, Course %>
        <ul class="nav pull-right">
          <li>
            <%= link_to "Switch to Course Admin View", manage_courses_path, :class => 'btn btn-success btn-mini admin_swtich_btn'%>
          </li>
        </ul>
	<% end %>
      </nav>
    </div>
  </div>
</div>

<script>
	<% flash.each do |key, value| %>
	    	$.jGrowl("<%= value %>");
	<% end %>
</script>
<% end %>

app/views/courses/_form.html.erb
<div class="container-fluid">
  <%= form_for @course, :html => {:multipart => true} do |f| %>

  <ul class="nav nav-tabs">
    <li class="active">
      <% if @course.id%>
      <%= link_to 'Basic Info', edit_course_path(@course) %>
      <% else %>
      <%= link_to 'Basic Info', new_course_path %>
      <% end %>
    </li>
    <% if @course.id%>
    <li>
      <%= link_to 'Modules', course_course_modules_path(@course) %>
    </li>
    <% end %>
  </ul>
  <% if @course.errors.any? %>
  <div class="row-fluid"><div class="span12">
    <div id="error_explanation">
      <ul>
        <% @course.errors.full_messages.each do |msg| %>
        <li>
          <%= msg %>
        </li>
        <% end %>
      </ul>
    </div>
  </div></div>
  <% end %>
  <div class="row-fluid">
    <div class="span6">
      <%= f.label :name %>
      <%= f.text_field :name, :class=>'input-full' %>

      <%= f.label :description %>
      <%= f.text_area :description, :class=>'input-full' %>

    </div>

    <div class="span6">

      <%= f.label 'Tag List (Comma Separated)'%>
      <%= f.autocomplete_field :tag_list, autocomplete_tag_name_courses_path, :"data-delimiter" => ', ', :class=>'input-text'  %>

      <%= f.label :category %>
      <%= select :course, :category, [['Choose One', ''], ['Comedy', 'Comedy'], ['Education', 'Education'], ['Entertainment', 'Entertainment']],{}, { :class => 'input-full' } %>

      <%= f.label :privacy %>
      <%= select :course, :privacy, [["Choose One", ""], ["Public", "Public"], ["Private", "Private"]],{},{ :class => 'input-full' } %>
    </div>
    <div class="actions">
      <%= f.submit "Save", :class => "btn btn-primary" %>
      <% if @course.id && !@course.published %>
        <%= f.submit "Publish and Save", :name => "publish", :class => "btn btn-success", :confirm => "Are you sure you want to Publish?" %>
      <% elsif @course.id && @course.published %>
        <%= f.submit "Un-Publish and Save", :name => "un_publish", :class => "btn btn-warning", :confirm => "Are you sure you want to Un-Publish?" %>
      <% end %>
      
      <% if @course.id %>
        <%= render :partial => 'courses/share_on_facebook' %>
      <% else %>
        <%= "You can share on Facebook after you save." %>
      <% end %>
    </div>

  </div>

  <% end %>
</div>

app/views/courses/_share_on_facebook.html.erb
<script>
function fbs_click() {u='<%=request.host+course_path(@course)%>';t=document.title;window.open('http://www.facebook.com/sharer.php?u='+encodeURIComponent(u)+'&t='+encodeURIComponent(t),'sharer','toolbar=0,status=0,width=626,height=436');return false;}
</script>
<style>
html .fb_share_link { padding:2px 0 0 20px; height:16px; background:url(http://static.ak.facebook.com/images/share/facebook_share_icon.gif?6:26981) no-repeat top left; }
</style>
<a rel="nofollow" href="http://www.facebook.com/share.php?u=<%=course_path(@course)%>" onclick="return fbs_click()" target="_blank" class="fb_share_link">Share on Facebook</a>

app/views/courses/course_landing.html.erb
<h2>Course Landing</h2>

<ul class="course_landing">
  <li>
    <%= link_to(t('My Courses'), my_courses_path)%>
  </li>
  <li>
    <%= link_to(t('Courses Catalog'), courses_path)%>
  </li>
  <li>
    <%= link_to(t('Manage Courses'), manage_courses_path)%>
  </li>
</ul>

app/views/courses/edit.html.erb
<%= render 'courses_admin_menu', :highlight => "courses" %>
<%= render 'form' %>

app/views/courses/index.html.erb
<%= render 'courses_menu', :highlight => "courses" %>
<ul class="courses">
  <% 
  if @courses.empty? 
    %>
      No Courses. 
    <%
  end
@courses.each do |course| %>
  
	<li>
	  <div class="title">
	   <span><%= link_to course.name, course_path(course) %></span>
	  </div>
	  <div class="description"><%= course.description %></div>
	  <span class="created_at"><%= course.created_at.to_formatted_s(:long) %></span>
	  <%= ratings_for course, :static %>
	  <div class="commands">
      <ul>
        <li>
          <%= link_to 'Start Course', course_path(course) %>
        </li>
      </ul>
    </div>
	</li>
  
<% end %>
</ul>

app/views/courses/manage.html.erb
<%= render 'courses_admin_menu', :highlight => "courses" %>

<div class="container-fluid user_courses_container">
  <div class="row-fluid">
    <div class="span9">
      <table class="table table-hover">
        <tbody>
          <% 
          if @courses.empty? 
            %>
              <tr><td>No Courses.</td></tr> 
            <%
          end
          @courses.each do |course| %>
            <tr>
              <td>
                <div class="title"><%= link_to course.name, :controller => "courses", :action => "edit", :id => course%></div>
                <div><%= course.course_modules.size%> Modules</div>
                <% if course.published %>
                  <span class="label label-success">Published</span>
                <% else %>
                  <span class="label">Draft</span>
                <% end %>
                <span class="created_at"><%= course.created_at.strftime("%b %d, %Y %I:%M %p") %></span>
			<%= ratings_for course, :static %>
              </td>
              <td class="commands">
                <%= link_to 'View Statistics', :controller => "statistics", :action => "index", :id => course%>
              </td>
		  <td class="commands">
			<%= link_to "Course Forums", :controller => "forums", :action => "index", :course_id => course %>
		  </td>

            </tr>
          <% end %>
        </tbody>
      </table>      
    </div>
    
	 <% if can? :create, Course %>
	     <div class="span3">
	     		<%= link_to 'Create New Course', {:controller => "courses", :action => "new"}, :class => 'btn btn-primary' %> 
     	     </div>
	<% end %>
   
  </div>
</div>

app/views/courses/my_courses.html.erb
<%= render 'courses_menu', :highlight => 'courses'%>

<div class="container-fluid user_courses_container">
  <div class="row-fluid">
    <div class="span12">
      <h3>In Progress</h3>
    </div>
  </div>
  <div class="row-fluid">
    <div class="span12">
      <table class="table table-hover">
        <tbody>
          <% 
          if @course_histories.empty? 
            %>
              <tr><td>No Courses.</td></tr> 
            <%
          end
          @course_histories.each do |course_history| 
            course = course_history.course
            %>  
            <tr>
              <td>
                <div class="title"><%= link_to course.name, :controller => "courses", :action => "start", :id => course %></div>
                
                <div class="description"><%= truncate course.description, :length => 300 %></div>
                <span class="status"><%= course_history.status %></span> - <span class="created_at"><%= course.created_at.to_formatted_s(:long) %></span>
                <%= ratings_for course, :static %>
                  
                <span class="status">
                  <%
                  if course_history.status == "in_progress"
                  %>
                    <span class="label label-warning">In Progress</span>
                  <% else %>
                    <span class="label label-success">Complete</span>
                  <% end %>
                </span>
                <span class="created_at">
                  <%= course.created_at.to_formatted_s(:long) %>
                </span>

              </td>
              <td nowrap>
                <%= link_to course_history.status == "completed"?'Review Course':'Resume Course', :controller => "courses", :action => "start", :id => course %>
              </td>
		  <td nowrap>
			<%= link_to "Course Forums", :controller=>"forums", :action=>"index", :course_id=>course %>
		  </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<div class="container-fluid">
  <div class="row-fluid">
    <div class="span12">
      <h3>Bookmarked Courses</h3>
    </div>
  </div>
  <div class="row-fluid">
    <div class="span12">
      <table class="table table-hover">
        <tbody>
          <% 
          if @bookmarks.empty? 
            %>
              <tr><td>No Courses Bookmarked.</td></tr> 
            <%
          end
          @bookmarks.each do |bookmark| 
            course = bookmark.course %>
            <tr>
              <td>
                <div class="title"><%= link_to course.name, course_path(course) %></div>
                <div class="description"><%= truncate course.description, :length => 300 %></div>
                <%= ratings_for course, :static %>
              </td>
              <td nowrap>
                <%= link_to 'View Course', course_path(course) %><br/>
                <%= link_to "Remove Bookmark", course_path(course)+"/bookmark?remove=true" %><br/>
                <%= link_to "Course Forums", :controller => "forums", :action => "index", :course_id => course %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>      
    </div>
  </div>
</div>


app/views/courses/new.html.erb
<%= render 'courses_admin_menu', :highlight => "courses" %>

<%= render 'form' %>

app/views/courses/rate.html.erb
<%= ratings_for @course, current_user %>

app/views/courses/show.html.erb
<%= render 'courses_admin_menu', :highlight => "courses" %>

<div class="container-fluid course-view">
  <div class="row-fluid">
    <div class="span12">
      <h3><%=@course.name %></h3>
      <div class="actions">
        <% 
        bookmark = current_user.bookmarks.where(:course_id => @course.id).first
        if !bookmark %>
          <%= link_to "Bookmark", course_path(@course)+"/bookmark", :class => "btn btn-primary bookmark", :remote => true %>
        <% else %>
          <span class="label">bookmarked</span>
        <% end %>
      <%= link_to "Start", {:controller => "courses", :action => "start", :id => @course}, :class => "btn btn-success" %>
      </div>
      <p>
        <%= @course.description %>
      </p>
      <p>
      	<b>Course Rating:</b> <%= ratings_for @course, :static %>	
      </p>

    </div>
  </div>
  <div class="row-fluid">
    <div class="span12">
      <b>Modules:</b>
      <table class="table table-hover">
        <tbody>
          <% 
          @course.course_modules.each_with_index do |course_module, index|
          %>
          <tr>
            <td><span>Part <%= index + 1 %></span> - <%= course_module.name %> (<%=course_module.class_type %>)
            <p><%= course_module.summary %></p>  
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/courses/start.html.erb
<%= render 'courses_menu', :highlight => "courses"  %>
<div class="container-fluid course-play-container">
  <div class="row-fluid">
    <div class="span12">
      <h3><%=@course.name %></h3>
      <p>
        <%= @course.description %>
      </p>
      <p>
		<% if @course.user_id != current_user.id %>
	      	<b>Course Rating:</b> <%= ratings_for @course, current_user %>
		<% else %>
			<b>Course Rating:</b> <%= ratings_for @course, :static %>
		<% end %>
      </p>

    </div>
  </div>
  <div class="row-fluid">
    <div class="span12">
      <b>Modules:</b>
      <table class="table table-hover">
        <tbody>
          <% 
          lastCompletedModule = @course_history.lastCompletedModule
          foundStartModule = false;
          @course.course_modules.each_with_index do |course_module, index|
            @module_history = @course_history.course_module_histories.where(:course_module_id => course_module.id).first
            if !@module_history
              @module_history = CourseModuleHistory.new
            end
            
            statusClass = @module_history.status
            if foundStartModule && !@module_history.id
              statusClass = "unavailable"
            end
          %>
          <tr class="<%= statusClass %>">
            <td><span>Part <%= index + 1 %></span> - <%= course_module.name %> (<%=course_module.class_type %>)</td>
            <td>
              <% if !foundStartModule || @module_history.id %>
              <div class="commands">
                <%= link_to @module_history.status == "in_progress" ? 'Resume':@module_history.status == "completed" ?"Review":"Start", course_course_module_path(@course, course_module) %>
              </div>
              <% end %>
            </td>
          </tr>
            <% if lastCompletedModule < course_module.position 
              foundStartModule = true
             end
            %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>



app/views/courses/test.html.erb
<% sidebar %>
        
<% toolbar %>

<br class="clearfloat" />
<div class="space_center">
</div>

<h2>This is a test page for the Video</h2>
<br>

<form action="">
	What is your favorite food?<br />
<input type="radio" name="food" value="tofu" /> Tofu<br />
<input type="radio" name="food" value="apples" /> Apples<br/></br/>

	What is your favorite video?<br />
<input type="radio" name="pref" value="call" /> The CallSource video<br />
<input type="radio" name="pref" value="jw" /> The JW Player video<br /><br />

<h2>Note: This is the end of the demo, this form is not functional</h2>

<%= button_to 'Submit', courses_path %>
</form>